{% set version = "0.2.5" %}

package:
  name: agate-excel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/agate-excel/agate-excel-{{ version }}.tar.gz
  sha256: 62315708433108772f7f610ca769996b468a4ead380076dbaf6ffe262831b153

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - agate >=1.5.0
    - openpyxl >=2.3.0
    - xlrd >=0.9.4

test:
  imports:
    - agateexcel

about:
  home: https://agate-excel.readthedocs.org/
  license_file: COPYING
  license: MIT
  license_family: MIT
  summary: agate-excel adds read support for Excel files (xls and xlsx) to agate.
  doc_url: https://agate-excel.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-excel

extra:
  recipe-maintainers:
    - pmlandwehr
