travis:
  secure:
    BINSTAR_TOKEN: MD2dJSwJK3Ky7KX/dbtVU6NkrE4LtUpi1TEFEeAbLkXYnqCh5fPkdv0mXqczKjsHhGia9/sh+a89LAInqiO/fd6q9KvKKSKKSWEGAKOCYynY/9f4MFuJq4NlqbK+cxaurffbfG03u/EIirMspdn7HtYUxqP6vrDR1DrLQ//4cPjt7oyeEEyVNizTphJQzpyu+MGUHIL3T5kH38RU2HSfeLaZLZPZte+onM/4P4QEOLbJ7l4CxsrI0UYzIA5CyKRBkzg84s5t+02LgGgDzRfbfkTjxnRz4oQj/gDUNu2d7K+w1/QQ9dBH00uPmCpuXWZtwYyz0wjW2yjfIapb7AOgZbAGSMTDAJ29AydghhQhs2y/uwiOz/z4HUfu3aQa8JbAipq3grNQtogXRSTgiQL1hXp605iaTvK/pbXZ6sox0bBpYs3fkuQmQ7O8oGbARQKWoqrp8eJaVCFqgAHu9WpCq1DszmRxOlwTQ6fRlBeiKEE93aKft5jaFEzNGTXTXNxNwDer3h+oZpMgXdFqbxj3u0fflATFrxQqu71XOt1WtqS000+ZxcfnmXFS9e/6VbMtEG6btx2ktSk6fDULWTIaErYLEwQkQ7yGsEYyfyshPw0EuHq+Wx/JBJPitvAjXYlrh30eavoms4Lo9c0gDYbm6bLRWzwTxP2pEekw+f+HJc0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
